spring:
  application:
    name: scores
  datasource:
    url: jdbc:h2:file:./data/scores
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8111

de.flapdoodle.mongodb.embedded.version: 6.0.5

hibernate:
  show_sql: true