CREATE TABLE spel
(
    id       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sport_id INT,
    CONSTRAINT pk_spel PRIMARY KEY (id)
);

CREATE TABLE spel_speler
(
    speler_id INT NOT NULL,
    spel_id   INT NOT NULL
);

CREATE TABLE speler
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50),
    CONSTRAINT pk_speler PRIMARY KEY (id)
);

CREATE TABLE sport
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    naam VARCHAR(255),
    CONSTRAINT pk_sport PRIMARY KEY (id)
);

ALTER TABLE spel
    ADD CONSTRAINT FK_SPEL_ON_SPORT FOREIGN KEY (sport_id) REFERENCES sport (id);

ALTER TABLE spel_speler
    ADD CONSTRAINT fk_spespe_on_spel_entiteit FOREIGN KEY (spel_id) REFERENCES spel (id);

ALTER TABLE spel_speler
    ADD CONSTRAINT fk_spespe_on_speler_entiteit FOREIGN KEY (speler_id) REFERENCES speler (id);

insert into sport(naam)values('Snooker');
insert into sport(naam)values('Darts');